{{- define "frontend.deployment.tpl" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend
    spec:
      containers:
      - name: python
        image: python
        command: ["/opt/bin/init.sh"]
        volumeMounts:
        - name: {{ .Chart.Name }}-frontend
          mountPath: /opt/bin/init.sh
          subPath: init.sh
        - name: {{ .Chart.Name }}-frontend
          mountPath: /var/lib/www/cgi-bin/count.py
          subPath: count.py
      volumes:
      - name: {{ .Chart.Name }}-frontend
        configMap:
          name: {{ .Chart.Name }}-frontend
          defaultMode: 0755
{{- end -}}
