{{- include "backend.customConfigmap" (list . "www2.customConfigmap") -}}
{{- define "www2.customConfigmap" -}}
{{- if .Values.backend.customConfigmap.enabled -}}
data:
  {{- range $path, $_ :=  .Files.Glob  "config_files/**.py" }}
  {{ $path | trimPrefix "config_files/" }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{ end }}
{{- end -}}
{{- end -}}
