apiVersion: v2
name: www2
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "3.13.0"
dependencies:
  - name: frontend
    repository: file://../lib-frontend
    version: 0.0.1
  - name: backend
    repository: file://../lib-backend
    version: 0.0.1
  - name: redis
    repository: file://../lib-redis
    version: 0.0.1
