frontend:
  app: www2
  host: www2.unixworld.io

backend:
  app: www2
  customfiles:
    /opt/bin/init.sh: "init.sh"
  customfiles2:
    /var/lib/www/cgi-bin/reset.py: "reset.py"
  customConfigmap:
    enabled: true
